### ISSUE TITLE
这个是支持android 几的,  Android9 或者 Android10?

### ISSUE THREAD

**Issue by ghost** [spianmo/VirtualAppShell#2]

**Comment by spianmo** [comment]
安卓9和安卓10Preview2，安卓10稳定版和安卓11不支持，我这边项目里面已经支持到安卓10稳定版和安卓11Preview3了，暂时没办法剥离出来，过一段时间开源

**Comment by spianmo** [comment]
非官方版本VA，分支吧，商业版太贵，这个项目当前暂时不能称之为一个ShellStub，会向加载assets或者SD卡上任意APK文件发展

**Comment by ghost** [comment]
感谢这么快回复啊, 刚刚在 VIVO-Y50 上试用了一下, 微信好像不能识别 SIM 啊, 是我哪里用错了吗 -_-||, 
另外能否加下微信, 咱们沟通下技术

**Comment by spianmo** [comment]
> 感谢这么快回复啊, 刚刚在 VIVO-Y50 上试用了一下, 微信好像不能识别 SIM 啊, 是我哪里用错了吗 -_-||,
> 另外能否加下微信, 咱们沟通下技术

微信：Exec_VirtualAlloc
